# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in {{ cookiecutter.name }}.gemspec: : spec.add_runtime_dependency 'example', '~> 1.2'
gemspec

gem 'bundler', '~> 2.3'
gem 'pry', '~> 0.14'
gem 'rake', '~> 13.0'
gem 'rubocop', '~> 1.56'
gem 'rubocop-rake', '~> 0.6'
